import type { TemplateFile } from "../types";

export const baseTemplate: TemplateFile[] = [
  {
    path: "package.json",
    content: `{
  "name": "gstack-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^16.2.9",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/node": "^20.0.0",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "postcss": "^8.4.0",
    "tailwindcss": "^4.0.0",
    "@tailwindcss/postcss": "^4.0.0"
  }
}`
  },
  {
    path: "tsconfig.json",
    content: `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "incremental": true,
    "plugins": [
      {
        "name": "next",
      },
    ],
    "paths": {
      "@/*": ["./*"],
    },
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    ".next/dev/types/**/*.ts",
    "**/*.mts",
  ],
  "exclude": ["node_modules"],
}
`
  },
  {
    path: "next.config.ts",
    content: `import type { NextConfig } from "next";
import path from "path";

const nextConfig: NextConfig = {
  /* config options here */
  turbopack: {
    root: path.dirname(__dirname),
  },
};

export default nextConfig;
`
  },
  {
    path: "postcss.config.mjs",
    content: `const postcssConfig = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default postcssConfig;
`
  },
  {
    path: "app/globals.css",
    content: `@import "tailwindcss";
`
  },
  {
    path: "app/layout.tsx",
    content: `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "gstack app",
  description: "Generated by g-stack CLI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("font-sans", geistSans.variable, geistMono.variable)}
    >
      <body
        className={\`\${geistSans.variable} \${geistMono.variable} antialiased bg-background text-foreground\`}
      >
        {children}
      </body>
    </html>
  );
}
`
  }
];

export const plainHomepage = `import { KeyRound, LogIn, UserPlus } from "lucide-react";
import Link from "next/link";
import React from "react";

export default function Home() {
  const links = [
    { href: "/signin", label: "Sign in route", icon: LogIn },
    { href: "/signup", label: "Sign up route", icon: UserPlus },
    { href: "/reset-password", label: "Reset password route", icon: KeyRound },
  ];

  return (
    <div className="min-h-dvh">
      <div className="w-xl min-h-dvh mx-auto flex flex-col items-start justify-center gap-2">
        <div className="mb-5">
          <h2 className="text-3xl font-black mb-2">g-stack</h2>
          <p className="text-gray-500">
            NextJs 16, BetterAuth, Docker, PostgreSQL
          </p>
        </div>
        <p>
          A production-ready Next.js starter with end-to-end type safety, modern
          tooling, and batteries included.
        </p>
        <div className="w-full space-y-2 mb-3">
          <h2 className="font-medium">Explore added routes</h2>

          {links.map((link) => (
            <div
              key={link.href}
              className="w-full flex items-center text-sm justify-between border border-gray-200 rounded-xl p-2.5 px-3.5"
            >
              <div className="flex items-center gap-3.5">
                {link.icon && React.createElement(link.icon, { size: 16 })}
                <div>{link.label}</div>
              </div>
              <div>
                <Link href={link.href}>
                  <button className="h-7 gap-1 px-3 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2 border border-gray-200 hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground dark:bg-transparent dark:hover:bg-input/30 rounded-lg">
                    {link.href}
                  </button>
                </Link>
              </div>
            </div>
          ))}
        </div>
        <p>
          To get started, edit the{" "}
          <kbd className="pointer-events-none inline-flex h-5 w-fit min-w-5 items-center justify-center gap-1 rounded-lg bg-muted px-1 font-sans text-xs font-medium text-muted-foreground select-none in-data-[slot=input-group]:bg-input in-data-[slot=tooltip-content]:bg-background/20 in-data-[slot=tooltip-content]:text-background dark:in-data-[slot=tooltip-content]:bg-background/10 [&_svg:not([class*='size-'])]:size-3">
            page.tsx
          </kbd>{" "}
          file
        </p>
        <div className="mt-3">
          <Link href={"https://nextjs.org/docs"} target="_blank">
            <button className="h-8 gap-1.5 px-3 has-data-[icon=inline-end]:pr-2.5 has-data-[icon=inline-start]:pl-2.5 bg-gray-800 text-white hover:bg-gray-700/80 rounded-full text-sm">
              Read docs
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
}
`;

export const shadcnHomepage = `import { Button } from "@/components/ui/button";
import {
  Item,
  ItemActions,
  ItemContent,
  ItemMedia,
  ItemTitle,
} from "@/components/ui/item";
import { Kbd } from "@/components/ui/kbd";
import { KeyRound, LogIn, UserPlus } from "lucide-react";
import Link from "next/link";

export default function Home() {
  return (
    <div className="min-h-dvh">
      <div className="w-xl min-h-dvh mx-auto flex flex-col items-start justify-center gap-2">
        <div className="mb-5">
          <h2 className="text-3xl font-black mb-2">g-stack</h2>
          <p className="text-primary/70">
            NextJs 16, BetterAuth, Docker, PostgreSQL, shadcn/ui
          </p>
        </div>
        <p>
          A production-ready Next.js starter with end-to-end type safety, modern
          tooling, and batteries included.
        </p>
        <div className="w-full space-y-2 mb-3">
          <h2 className="font-medium">Explore added routes</h2>
          <Item variant={"outline"} size={"sm"}>
            <ItemMedia variant="icon">
              <LogIn />
            </ItemMedia>
            <ItemContent>
              <ItemTitle>Sign in route</ItemTitle>
            </ItemContent>
            <ItemActions>
              <Link href={"/signin"}>
                <Button variant={"outline"} size={"xs"}>
                  /signin
                </Button>
              </Link>
            </ItemActions>
          </Item>
          <Item variant={"outline"} size={"sm"}>
            <ItemMedia variant="icon">
              <UserPlus />
            </ItemMedia>
            <ItemContent>
              <ItemTitle>Sign up route</ItemTitle>
            </ItemContent>
            <ItemActions>
              <Link href={"/signup"}>
                <Button variant={"outline"} size={"xs"}>
                  /signup
                </Button>
              </Link>
            </ItemActions>
          </Item>
          <Item variant={"outline"} size={"sm"}>
            <ItemMedia variant="icon">
              <KeyRound />
            </ItemMedia>
            <ItemContent>
              <ItemTitle>Reset password route</ItemTitle>
            </ItemContent>
            <ItemActions>
              <Link href={"/reset-password"}>
                <Button variant={"outline"} size={"xs"}>
                  /reset-password
                </Button>
              </Link>
            </ItemActions>
          </Item>
        </div>
        <p>
          To get started, edit the <Kbd>page.tsx</Kbd> file
        </p>
        <div className="mt-3">
          <Link href={"https://nextjs.org/docs"} target="_blank">
            <Button>Read docs</Button>
          </Link>
        </div>
      </div>
    </div>
  );
}
`;

export const plainNotFound = `import Link from "next/link";

const LostIcon = () => {
  return (
    <svg
      aria-hidden="true"
      xmlns="http://www.w3.org/2000/svg"
      className="size-8"
      fill="currentColor"
      viewBox="0 0 256 256"
    >
      <path d="M176,140a12,12,0,1,1-12-12A12,12,0,0,1,176,140ZM128,92a12,12,0,1,0-12,12A12,12,0,0,0,128,92Zm73-38A104,104,0,0,0,50.48,197.33,8,8,0,1,0,62.4,186.66a88,88,0,1,1,131.19,0,8,8,0,0,0,11.93,10.67A104,104,0,0,0,201,54ZM152,168H136c-21.74,0-48-17.84-48-40a41.33,41.33,0,0,1,.55-6.68,8,8,0,1,0-15.78-2.64A56.9,56.9,0,0,0,72,128c0,14.88,7.46,29.13,21,40.15C105.4,178.22,121.07,184,136,184h16a8,8,0,0,1,0,16H96a24,24,0,0,0,0,48,8,8,0,0,0,0-16,8,8,0,0,1,0-16h56a24,24,0,0,0,0-48Z" />
    </svg>
  );
};

export default function NotFound() {
  return (
    <main className="min-h-dvh bg-white text-zinc-950">
      <div className="mx-auto flex min-h-dvh w-full max-w-sm items-center justify-center px-6">
        <section
          aria-labelledby="not-found-heading"
          className="w-full text-center"
        >
          <div className="mx-auto mb-5 flex size-12 items-center justify-center rounded-full bg-zinc-100 text-zinc-500">
            <LostIcon />
          </div>

          <div className="space-y-2">
            <p className="text-sm font-semibold text-zinc-500">404</p>
            <h1
              id="not-found-heading"
              className="text-lg font-semibold tracking-tight text-zinc-950"
            >
              Looks Like You&apos;re Lost
            </h1>
            <p className="mx-auto max-w-xs text-sm leading-6 text-zinc-500">
              The page you&apos;re trying to access doesn&apos;t exist or is no
              longer available.
            </p>
          </div>

          <div className="mt-6 flex items-center justify-center gap-3">
            <Link
              href="/"
              className="inline-flex h-7 items-center justify-center rounded-full bg-zinc-950 px-4 text-sm font-semibold text-white transition hover:bg-zinc-800 focus:outline-none focus:ring-2 focus:ring-zinc-300 focus:ring-offset-2"
            >
              Go home
            </Link>
            <Link
              href="/signin"
              className="inline-flex h-7 items-center justify-center rounded-full border border-zinc-200 bg-white px-4 text-sm font-semibold text-zinc-800 transition hover:bg-zinc-50 focus:outline-none focus:ring-2 focus:ring-zinc-300 focus:ring-offset-2"
            >
              Sign in
            </Link>
          </div>
        </section>
      </div>
    </main>
  );
}
`;

export const shadcnNotFound = `import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle,
} from "@/components/ui/empty";

export default function NotFound() {
  return (
    <div className="min-h-dvh w-full flex items-center justify-center">
      <Empty>
        <EmptyHeader>
          <EmptyMedia variant={"icon"}>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              fill="currentColor"
              viewBox="0 0 256 256"
            >
              <path d="M176,140a12,12,0,1,1-12-12A12,12,0,0,1,176,140ZM128,92a12,12,0,1,0-12,12A12,12,0,0,0,128,92Zm73-38A104,104,0,0,0,50.48,197.33,8,8,0,1,0,62.4,186.66a88,88,0,1,1,131.19,0,8,8,0,0,0,11.93,10.67A104,104,0,0,0,201,54ZM152,168H136c-21.74,0-48-17.84-48-40a41.33,41.33,0,0,1,.55-6.68,8,8,0,1,0-15.78-2.64A56.9,56.9,0,0,0,72,128c0,14.88,7.46,29.13,21,40.15C105.4,178.22,121.07,184,136,184h16a8,8,0,0,1,0,16H96a24,24,0,0,0,0,48,8,8,0,0,0,0-16,8,8,0,0,1,0-16h56a24,24,0,0,0,0-48Z"></path>
            </svg>
          </EmptyMedia>
          <EmptyTitle>Looks Like You&apos;re Lost</EmptyTitle>
          <EmptyDescription>
            The page you&apos;re trying to access doesn&apos;t exist or is no
            longer available.
          </EmptyDescription>
        </EmptyHeader>
      </Empty>
    </div>
  );
}
`;
