import type { TemplateFile } from "../types";

export const baseTemplate: TemplateFile[] = [
  {
    path: "package.json",
    content: JSON.stringify(
      {
        name: "gstack-app",
        version: "0.1.0",
        private: true,
        scripts: {
          "dev": "next dev",
          "build": "next build",
          "start": "next start",
          "lint": "next lint"
        },
        dependencies: {
          "next": "^15.1.0",
          "react": "^19.0.0",
          "react-dom": "^19.0.0"
        },
        devDependencies: {
          "typescript": "^5.0.0",
          "@types/node": "^20.0.0",
          "@types/react": "^19.0.0",
          "@types/react-dom": "^19.0.0",
          "postcss": "^8.4.0",
          "tailwindcss": "^4.0.0",
          "@tailwindcss/postcss": "^4.0.0"
        }
      },
      null,
      2
    )
  },
  {
    path: "tsconfig.json",
    content: JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [
            {
              name: "next"
            }
          ],
          paths: {
            "@/*": ["./*"]
          }
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"]
      },
      null,
      2
    )
  },
  {
    path: "next.config.ts",
    content: `import type { NextConfig } from "next";
import path from "path";

const nextConfig: NextConfig = {
  /* config options here */
  turbopack: {
    root: path.dirname(__dirname),
  },
};

export default nextConfig;
`
  },
  {
    path: "postcss.config.mjs",
    content: `const postcssConfig = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default postcssConfig;
`
  },
  {
    path: "tailwind.config.ts",
    content: `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
`
  },
  {
    path: "app/globals.css",
    content: `@import "tailwindcss";
`
  },
  {
    path: "app/layout.tsx",
    content: `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "g-stack Scaffolder App",
  description: "Generated by g-stack CLI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={\`\${geistSans.variable} \${geistMono.variable} antialiased bg-background text-foreground\`}>
        {children}
      </body>
    </html>
  );
}
`
  }
];

export const plainHomepage = `export default function Home() {
  return (
    <main className="flex min-h-dvh flex-col items-center justify-center bg-zinc-950 px-6 py-12">
      <div className="flex max-w-3xl w-full flex-col items-center gap-16 text-center">
        <div className="flex flex-col items-center gap-5">
          <div className="inline-flex items-center gap-2 rounded-full border border-zinc-800 bg-zinc-900/60 px-3 py-1 text-xs font-medium text-zinc-400">
            <span className="size-1.5 rounded-full bg-emerald-500" />
            Scaffolded successfully
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-white sm:text-5xl">
            Welcome to your g-stack app
          </h1>
          <p className="max-w-lg text-base leading-relaxed text-zinc-400">
            A production-ready Next.js application with type safety, modern
            routing, and your selected stack.
          </p>
        </div>

        <div className="grid w-full grid-cols-1 gap-px overflow-hidden rounded-lg border border-zinc-800 bg-zinc-800 sm:grid-cols-3">
          <div className="flex flex-col gap-2 bg-zinc-950 p-6">
            <h2 className="text-sm font-semibold text-white">App Router</h2>
            <p className="text-sm leading-relaxed text-zinc-400">
              Server Components, Server Actions, and file-based routing.
            </p>
          </div>
          <div className="flex flex-col gap-2 bg-zinc-950 p-6">
            <h2 className="text-sm font-semibold text-white">
              Authentication
            </h2>
            <p className="text-sm leading-relaxed text-zinc-400">
              Secure routes and API handlers with your chosen auth provider.
            </p>
          </div>
          <div className="flex flex-col gap-2 bg-zinc-950 p-6">
            <h2 className="text-sm font-semibold text-white">Database</h2>
            <p className="text-sm leading-relaxed text-zinc-400">
              Type-safe data access powered by PostgreSQL and Prisma ORM.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          <a
            href="/signin"
            className="inline-flex h-10 items-center rounded-md bg-white px-6 text-sm font-medium text-zinc-950 transition-colors hover:bg-zinc-200"
          >
            Get started
          </a>
          <a
            href="https://nextjs.org/docs"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex h-10 items-center rounded-md border border-zinc-800 bg-transparent px-6 text-sm font-medium text-zinc-300 transition-colors hover:bg-zinc-900"
          >
            Documentation
          </a>
        </div>
      </div>
    </main>
  );
}
`;

export const shadcnHomepage = `import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

export default function Home() {
  return (
    <main className="flex min-h-dvh flex-col items-center justify-center bg-background px-6 py-12">
      <div className="flex max-w-3xl w-full flex-col items-center gap-16 text-center">
        <div className="flex flex-col items-center gap-5">
          <div className="inline-flex items-center gap-2 rounded-full border border-border bg-muted/50 px-3 py-1 text-xs font-medium text-muted-foreground">
            <span className="size-1.5 rounded-full bg-emerald-500" />
            Scaffolded successfully
          </div>
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
            Welcome to your g-stack app
          </h1>
          <p className="max-w-lg text-base leading-relaxed text-muted-foreground">
            A production-ready Next.js application with type safety, modern
            routing, and your selected stack.
          </p>
        </div>

        <div className="grid w-full grid-cols-1 gap-4 text-left sm:grid-cols-3">
          <Card>
            <CardHeader>
              <CardTitle className="text-sm">App Router</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Server Components, Server Actions, and file-based routing.
              </CardDescription>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle className="text-sm">Authentication</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Secure routes and API handlers with your chosen auth provider.
              </CardDescription>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle className="text-sm">Database</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Type-safe data access powered by PostgreSQL and Prisma ORM.
              </CardDescription>
            </CardContent>
          </Card>
        </div>

        <div className="flex items-center gap-3">
          <a href="/signin">
            <Button size="lg">Get started</Button>
          </a>
          <a
            href="https://nextjs.org/docs"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Button variant="outline" size="lg">
              Documentation
            </Button>
          </a>
        </div>
      </div>
    </main>
  );
}
`;
